# Generated by Django 3.2.16 on 2023-09-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_app', '0002_registered_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered_user',
            name='address',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='registered_user',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='registered_user',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='registered_user',
            name='date_created',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='registered_user',
            name='day_of_birth',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Day Of Birth'),
        ),
        migrations.AlterField(
            model_name='registered_user',
            name='domain_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Domain Name'),
        ),
        migrations.AlterField(
            model_name='registered_user',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='registered_user',
            name='expiration_date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Expiration Date'),
        ),
        migrations.AlterField(
            model_name='registered_user',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Firstname'),
        ),
        migrations.AlterField(
            model_name='registered_user',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='registered_user',
            name='hsDomainsDataID',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Domain Data ID'),
        ),
        migrations.AlterField(
            model_name='registered_user',
            name='hsUsersID',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='registered_user',
            name='hs_product_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Product ID'),
        ),
        migrations.AlterField(
            model_name='registered_user',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='registered_user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lastname'),
        ),
        migrations.AlterField(
            model_name='registered_user',
            name='last_transaction_date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Last Transaction Date'),
        ),
        migrations.AlterField(
            model_name='registered_user',
            name='manager_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Manager Company Name'),
        ),
        migrations.AlterField(
            model_name='registered_user',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mobile Phone'),
        ),
        migrations.AlterField(
            model_name='registered_user',
            name='month_of_birth',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Month Of Birth'),
        ),
        migrations.AlterField(
            model_name='registered_user',
            name='product',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Product Description'),
        ),
        migrations.AlterField(
            model_name='registered_user',
            name='reseller_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Reseller Company Name'),
        ),
        migrations.AlterField(
            model_name='registered_user',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='registered_user',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='registered_user',
            name='year_of_birth',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Year Of Birth'),
        ),
        migrations.AlterField(
            model_name='registered_user',
            name='zip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Zip'),
        ),
    ]
