# Generated by Django 4.0.6 on 2022-07-28 04:49

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_app', '0002_category_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='myfield',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
