# Generated by Django 3.2.16 on 2023-10-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_app', '0003_auto_20230927_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country Code')),
                ('country_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country Name')),
            ],
        ),
    ]
