# Generated by Django 3.2.16 on 2023-10-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_app', '0004_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='registered_user',
            name='payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registered_user',
            name='status_descript',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status Description'),
        ),
    ]
