# Generated by Django 4.0.6 on 2022-12-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_app', '0005_remove_customuser_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='site',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
