# Generated by Django 3.2.16 on 2023-10-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_app', '0005_auto_20231001_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('domain_id', models.CharField(blank=True, max_length=15, null=True, verbose_name='Domain ID')),
                ('url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Captive Portal API URL')),
                ('endpoint', models.CharField(blank=True, max_length=100, null=True, verbose_name='Captive Portal API Endpoint')),
                ('api_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='Captive Portal API Key')),
                ('api_seceret', models.CharField(blank=True, max_length=100, null=True, verbose_name='Captive Portal API Secret')),
                ('last_extracted_date', models.DateTimeField(blank=True, null=True, verbose_name='Date Last Extracted From')),
                ('omnisend_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Omnisend URL')),
                ('omnisend_endpoint', models.CharField(blank=True, max_length=100, null=True, verbose_name='Omnisend Endpoint')),
                ('omnisend_api_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='Omnisend API Key')),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
