# Generated by Django 3.2.16 on 2023-10-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_app', '0006_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('domain_id', models.CharField(blank=True, max_length=15, null=True, verbose_name='Domain ID')),
                ('last_extracted_date', models.DateTimeField(blank=True, null=True, verbose_name='Date Last Extracted From')),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('extracted', models.BooleanField(default=False, verbose_name='Extracted Status')),
            ],
        ),
    ]
