# Generated by Django 3.2.16 on 2023-10-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_app', '0007_domain_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered_user',
            name='status_descript',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Status Description'),
        ),
    ]
