# Generated by Django 4.0.6 on 2022-12-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_app', '0008_customuser_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='site',
            field=models.CharField(blank=True, max_length=30, verbose_name='last name'),
        ),
    ]
