# Generated by Django 3.2.16 on 2023-11-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_app', '0009_core_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consolidated_Core_Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reseller_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reseller Company Name')),
                ('manager_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Manager Company Name')),
                ('domain_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Domain Name')),
                ('insertion_date', models.DateTimeField(blank=True, null=True, verbose_name='Insertion Date ')),
                ('question_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Question Type')),
                ('surveyID', models.CharField(blank=True, max_length=100, null=True, verbose_name='Survey ID')),
                ('hsUsersID', models.CharField(blank=True, max_length=100, null=True, verbose_name='User ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Firstname')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lastname')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Name')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('address', models.CharField(blank=True, max_length=400, null=True, verbose_name='Address')),
                ('zip', models.CharField(blank=True, max_length=100, null=True, verbose_name='Zip')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country')),
                ('gender', models.CharField(blank=True, max_length=100, null=True, verbose_name='Gender')),
                ('year_of_birth', models.CharField(blank=True, max_length=100, null=True, verbose_name='Year Of Birth')),
                ('month_of_birth', models.CharField(blank=True, max_length=100, null=True, verbose_name='Month Of Birth')),
                ('day_of_birth', models.CharField(blank=True, max_length=100, null=True, verbose_name='Day Of Birth')),
                ('room_or_site', models.CharField(blank=True, max_length=100, null=True, verbose_name='Room Or Site')),
                ('hs_product_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Product ID')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone')),
                ('mobile_phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mobile Phone')),
                ('conditions_accepted', models.CharField(blank=True, max_length=10, null=True, verbose_name='Conditions Accepted')),
                ('privacy_policyAccepted', models.CharField(blank=True, max_length=10, null=True, verbose_name='Privacy PolicyAccepted')),
                ('marketing_accepted', models.CharField(blank=True, max_length=10, null=True, verbose_name='Marketing Accepted')),
                ('newsletters_accepted', models.CharField(blank=True, max_length=10, null=True, verbose_name='Newsletters Accepted')),
                ('q_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Question 1')),
                ('q_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Question 2')),
                ('q_3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Question 3')),
                ('q_4', models.CharField(blank=True, max_length=100, null=True, verbose_name='Question 4')),
                ('score', models.CharField(blank=True, max_length=100, null=True, verbose_name='Score')),
                ('date_consolidated', models.DateTimeField(blank=True, null=True, verbose_name='Date Consolidated')),
            ],
        ),
    ]
