# Generated by Django 4.0.6 on 2022-12-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_app', '0010_remove_customuser_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='extra_field',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
