# Generated by Django 3.2.16 on 2023-11-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_app', '0010_consolidated_core_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='core_quiz',
            name='consolidated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='core_quiz',
            name='date_consolidated',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Consolidated'),
        ),
    ]
