# Generated by Django 4.0.6 on 2022-12-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_app', '0011_customuser_extra_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='site',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
