# Generated by Django 3.2.16 on 2023-11-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_app', '0012_auto_20231101_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolidated_core_quiz',
            name='product',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Interested Product'),
        ),
    ]
