# Generated by Django 3.2.16 on 2023-11-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_app', '0013_consolidated_core_quiz_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload_Interval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.CharField(blank=True, choices=[(1, 1), (3, 3), (6, 6), (12, 12), (24, 24), (48, 48), (96, 96)], default=24, max_length=3, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='consolidated_core_quiz',
            name='status_descript',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Status Description'),
        ),
    ]
