# Generated by Django 3.2.16 on 2023-11-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_app', '0014_auto_20231101_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_interval',
            name='interval',
            field=models.CharField(blank=True, choices=[('1', 1), ('3', 3), ('6', 6), ('12', 12), ('24', 24), ('48', 48), ('96', 96)], default=24, max_length=3, null=True),
        ),
    ]
