# Generated by Django 3.2.16 on 2023-01-10 09:00

from django.db import migrations, models
import wifi_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_app', '0016_alter_topic_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='cell_number',
            field=models.CharField(default=726124698, max_length=10, validators=[wifi_app.models.validate_length]),
            preserve_default=False,
        ),
    ]
