# Generated by Django 3.2.16 on 2023-11-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_app', '0017_alter_consolidated_core_quiz_q_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolidated_core_quiz',
            name='q_5',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Question 5'),
        ),
        migrations.AlterField(
            model_name='consolidated_core_quiz',
            name='q_4',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Question 4'),
        ),
    ]
