# Generated by Django 3.2.16 on 2023-01-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_app', '0017_comment_cell_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='notify',
            field=models.BooleanField(default=False),
        ),
    ]
