# Generated by Django 3.2.16 on 2023-11-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_app', '0018_auto_20231108_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='core_quiz',
            name='q_5',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Question 5'),
        ),
    ]
