# Generated by Django 3.2.16 on 2023-12-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_app', '0019_core_quiz_q_5'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description')),
                ('domain_id', models.CharField(blank=True, max_length=15, null=True, verbose_name='Domain ID')),
                ('survey_id', models.CharField(blank=True, max_length=15, null=True, verbose_name='Survey ID')),
                ('creation_date', models.DateTimeField(blank=True, null=True, verbose_name='Creation Date')),
                ('is_active', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='core_quiz',
            name='personal_info',
            field=models.BooleanField(default=False),
        ),
    ]
