# Generated by Django 3.2.16 on 2023-12-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_app', '0020_auto_20231210_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='core_quiz',
            name='domain_id',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Domain ID'),
        ),
    ]
