# Generated by Django 3.2.16 on 2024-01-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_app', '0021_core_quiz_domain_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='core_quiz',
            name='date_extracted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Extracted From Captive Portal'),
        ),
    ]
