# Generated by Django 3.2.16 on 2024-01-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_app', '0022_core_quiz_date_extracted'),
    ]

    operations = [
        migrations.AddField(
            model_name='core_quiz',
            name='date_personal_info',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Personal Info Updated'),
        ),
    ]
