# Generated by Django 3.2.16 on 2024-03-05 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_app', '0023_core_quiz_date_personal_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolidated_core_quiz',
            name='sms_date_sent',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Date SMS Text'),
        ),
        migrations.AddField(
            model_name='consolidated_core_quiz',
            name='sms_received_date',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Date SMS Response Received'),
        ),
        migrations.AddField(
            model_name='consolidated_core_quiz',
            name='sms_received_meta',
            field=models.TextField(blank=True, null=True, verbose_name='SMS Response Meta Info'),
        ),
        migrations.AddField(
            model_name='consolidated_core_quiz',
            name='sms_received_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SMS Received Text'),
        ),
        migrations.AddField(
            model_name='consolidated_core_quiz',
            name='sms_sent_meta',
            field=models.TextField(blank=True, null=True, verbose_name='SMS Sent Meta Info'),
        ),
        migrations.AddField(
            model_name='consolidated_core_quiz',
            name='sms_sent_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SMS Text'),
        ),
    ]
