# Generated by Django 3.2.16 on 2024-03-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_app', '0024_auto_20240305_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consolidated_core_quiz',
            name='sms_sent_text',
            field=models.TextField(blank=True, null=True, verbose_name='SMS Text'),
        ),
    ]
