# Generated by Django 3.2.16 on 2024-03-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_app', '0025_alter_consolidated_core_quiz_sms_sent_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
