# Generated by Django 3.2.16 on 2024-03-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_app', '0030_alter_gameuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameuser',
            name='display_name',
            field=models.CharField(max_length=100, verbose_name='Your Username'),
        ),
        migrations.AlterField(
            model_name='gameuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='gameuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='gameuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Surname'),
        ),
    ]
