# Generated by Django 3.2.16 on 2024-03-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_app', '0031_auto_20240315_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook_log',
            name='hssurveysid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Survey ID'),
        ),
        migrations.AddField(
            model_name='webhook_log',
            name='hsuserid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Survey's User ID"),
        ),
        migrations.AddField(
            model_name='webhook_log',
            name='type',
            field=models.CharField(default='Email', max_length=10, verbose_name='SMS or Email'),
        ),
    ]
