# Generated by Django 3.2.16 on 2024-03-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_app', '0033_auto_20240323_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolidated_core_quiz',
            name='client',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='survey_settings',
            name='client_api',
            field=models.CharField(choices=[('OM', 'OM'), ('DC', 'DC'), ('TT', 'TT')], default='TT', max_length=15, verbose_name='Client API'),
        ),
    ]
