# Generated by Django 3.2.16 on 2024-03-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_app', '0034_auto_20240324_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook_log',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='User Name'),
        ),
    ]
