# Generated by Django 4.0.6 on 2022-10-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utm_1', models.TextField(blank=True, null=True)),
                ('utm_2', models.TextField(blank=True, null=True)),
                ('utm_3', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('page', models.TextField(blank=True, null=True)),
                ('counter', models.IntegerField(default=0)),
                ('session', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
