# Generated by Django 4.0.6 on 2022-12-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0002_remove_activation_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='date_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Activated'),
        ),
    ]
