# Generated by Django 4.0.6 on 2022-12-05 15:03

from django.db import migrations, models
import vouchers.models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0003_alter_activation_date_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='cell_number',
            field=models.IntegerField(validators=[vouchers.models.validate_length]),
        ),
    ]
