# Generated by Django 4.0.6 on 2022-12-05 15:21

from django.db import migrations, models
import vouchers.models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0004_alter_activation_cell_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='cell_number',
            field=models.CharField(max_length=10, validators=[vouchers.models.validate_length]),
        ),
    ]
