# Generated by Django 4.0.6 on 2022-12-06 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0005_alter_activation_cell_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
