# Generated by Django 3.2.16 on 2022-12-06 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0006_alter_activation_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='voucher',
            old_name='voucher_text',
            new_name='company_name',
        ),
        migrations.AddField(
            model_name='activation',
            name='voucher_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vouchers.vouchertype', verbose_name='Voucher Type'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='voucher_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vouchers.vouchertype', verbose_name='Voucher Type'),
        ),
    ]
