# Generated by Django 3.2.16 on 2022-12-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0008_auto_20221206_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='activation',
            name='voucher_nr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
