# Generated by Django 3.2.16 on 2022-12-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0009_activation_voucher_nr'),
    ]

    operations = [
        migrations.AddField(
            model_name='activation',
            name='user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
